### ISSUE TITLE
Questions about contributions.

### ISSUE THREAD

**Issue by adnene-guessoum** [dsgibbons/shap#106]
So, to keep contributing, should it be done here or at the original shap. Are you guys maintainers with write access there now ?

Thx for the good work.

**Comment by thatlittleboy** [comment]
Hi @adnene-guessoum , thank you for your interest. Future contributions can now be raised back at the main repo. You may read https://github.com/slundberg/shap/discussions/2942 for more info.

In short, we have write/push access to `slundberg/shap` so we can review/merge your PRs there directly; but we're also discussing with slundberg to set up a shap organization, so we can better collaborate as a community together.

**Comment by dsgibbons** [comment]
@thatlittleboy is right. Please direct any future contributions to `slundberg/shap`. Thank you for your help with this fork!
