### ISSUE TITLE
Invite open PRs from slundberg/shap to contribute

### ISSUE THREAD

**Issue by dsgibbons** [dsgibbons/shap#2]
## Latest PRs to invite
The authors of the following open PRs should be invited to contribute to this fork. Ticked items are considered done for the purposes of this issue.

✉️ indicates an email has been sent. Items without this emoji did not have an obvious contact email.
✅ indicates a PR has been raised. 
❓ indicates that we don't intend to raise a PR without further input from the PR's author.
❌ indicates the PR is out-of-date and will not be considered.

- [x] https://github.com/slundberg/shap/pull/1890 ✉️ ✅
- [x] https://github.com/slundberg/shap/pull/1897 ❓
- [x] https://github.com/slundberg/shap/pull/1927 ✅
- [x] https://github.com/slundberg/shap/pull/1931 ✉️ ❌
- [ ] https://github.com/slundberg/shap/pull/1944 ❓
- [x] https://github.com/slundberg/shap/pull/2006 ✉️❓
- [ ] https://github.com/slundberg/shap/pull/2020 ✉️
- [x] https://github.com/slundberg/shap/pull/2048 ✅
- [x] https://github.com/slundberg/shap/pull/2056 ❓
- [x] https://github.com/slundberg/shap/pull/2123 ✉️ ✅
- [x] https://github.com/slundberg/shap/pull/2155❓
- [x] https://github.com/slundberg/shap/pull/2166 ✉️ ✅
- [ ] https://github.com/slundberg/shap/pull/2169
- [ ] https://github.com/slundberg/shap/pull/2225
- [x] https://github.com/slundberg/shap/pull/2280❓
- [ ] https://github.com/slundberg/shap/pull/2290
- [ ] https://github.com/slundberg/shap/pull/2452 ✉️
- [ ] https://github.com/slundberg/shap/pull/2473
- [ ] https://github.com/slundberg/shap/pull/2549
- [x] https://github.com/slundberg/shap/pull/2594 ✉️ ✅
- [x] https://github.com/slundberg/shap/pull/2595 ✉️ ✅
- [ ] https://github.com/slundberg/shap/pull/2602 ✉️
- [ ] https://github.com/slundberg/shap/pull/2604 ✉️
- [ ] https://github.com/slundberg/shap/pull/2624 ✉️
- [x] https://github.com/slundberg/shap/pull/2641 ✅
- [x] https://github.com/slundberg/shap/pull/2649 ✅
- [ ] https://github.com/slundberg/shap/pull/2654
- [x] https://github.com/slundberg/shap/pull/2655 ✅
- [ ] https://github.com/slundberg/shap/pull/2667 ✉️
- [x] https://github.com/slundberg/shap/pull/2672 ✉️ ✅
- [ ] https://github.com/slundberg/shap/pull/2679 ✉️
- [x] https://github.com/slundberg/shap/pull/2683 ❓
- [ ] https://github.com/slundberg/shap/pull/2696
- [x] https://github.com/slundberg/shap/pull/2697 ✉️ ❓ 
- [ ] https://github.com/slundberg/shap/pull/2700
- [ ] https://github.com/slundberg/shap/pull/2710 ✉️
- [x] https://github.com/slundberg/shap/pull/2726 ✅
- [x] https://github.com/slundberg/shap/pull/2748 ❓
- [x] https://github.com/slundberg/shap/pull/2769 ✉️ ✅
- [x] https://github.com/slundberg/shap/pull/2792 ✉️ ❌
- [ ] https://github.com/slundberg/shap/pull/2799 ✉️
- [ ] https://github.com/slundberg/shap/pull/2807 ✉️
- [ ] https://github.com/slundberg/shap/pull/2812
- [x] https://github.com/slundberg/shap/pull/2830 ✅
- [ ] https://github.com/slundberg/shap/pull/2833
- [ ] https://github.com/slundberg/shap/pull/2834
- [ ] https://github.com/slundberg/shap/pull/2839
- [x] https://github.com/slundberg/shap/pull/2848 ✉️❓
- [x] https://github.com/slundberg/shap/pull/2873 ✉️❓
- [ ] https://github.com/slundberg/shap/pull/2877
- [x] https://github.com/slundberg/shap/pull/2885 ✅
- [x] https://github.com/slundberg/shap/pull/2890 ✅
- [x] https://github.com/slundberg/shap/pull/2912 ✉️ ✅
- [ ] https://github.com/slundberg/shap/pull/2915
- [x] https://github.com/slundberg/shap/pull/2924 ✅

**Comment by 11301858** [comment]
Hi, I'm the contributor for the last pull request on your list. May I ask what the purpose of this fork is?

**Comment by dsgibbons** [comment]
Please see the discussion [here](https://github.com/dsgibbons/shap/discussions/1) and feel free to ask questions there. Assuming slundberg/shap is no longer active, I'm looking for developers to help maintain and improve this fork of shap.

**Comment by 11301858** [comment]
Hello,

I will be glad to contribute! Thank you for letting me know of this
opportunity. Mr. Lundberg still seems to be active, but I support the
purpose of your work. Perhaps we can keep Mr. Lundberg in the loop just so
that he knows what we're doing.

Thanks,
Shreyan

**Comment by ekrell** [comment]
Hello! Stumbled on this today, and I would love to see progress on the SHAP library and appreciate your effort to get this going. 
I am the author of `PartitionShap: channel-first partitioning and channel SHAP plots.` 
Let me know how I can help. 

-- Evan Krell (ekrell@islander.tamucc.edu)

**Comment by dsgibbons** [comment]
Hi Evan, great to hear from you. I'm looking to establish a community of maintainers so that we can share the load long-term. Do you know other developers that would be interested in helping out with this project?

**Comment by prabathbr** [comment]
Hi Thanks for the invite,  I have raised https://github.com/dsgibbons/shap/pull/100 PR for issue "https://github.com/slundberg/shap/pull/2890"
