### ISSUE TITLE
Expose `n_points` to all other datasets

### ISSUE THREAD

**Issue by thatlittleboy** [dsgibbons/shap#35]
The `shap.datasets.california()` function has an `n_points` parameter that the rest of the datasets don't.

1. I think it's quite a convenient to have this parameter (mostly for internal use, especially when we want to keep tests/docs minimal.).
2. This also has the benefit of unifying the API for all the datasets that we expose.

**Comment by dsgibbons** [comment]
Sounds good. I've raised a related issue at #37 regarding the `display` kwarg. It would be nice to have a consistent API across the datasets.
