### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by dsgibbons** [dsgibbons/shap#4]
## Problem

The tests run by GitHub actions always fail. There appear to be multiple failures that contribute to this. Individual issues will be raised regarding each failure condition.

## Success criterion

Refactor the code, dependencies and tests so that all tests run successfully.

**Comment by connortann** [comment]
I think we're most of the way there now, just some matplotlib issues to sort.

I had a go reproducing the failing image diff tests locally (`tests.plots.test_heatmap`): it looks like the heatmap plot is now currently being plotted a bit vertically lower in the figure:

![image](https://github.com/dsgibbons/shap/assets/71127464/700eb2fe-a61c-4e99-8bc0-1ec94474b6f9)

**Comment by dsgibbons** [comment]
Oh I was literally just working on this! I'm about to open a PR

**Comment by dsgibbons** [comment]
See [https://github.com/dsgibbons/shap/pull/29](https://github.com/dsgibbons/shap/pull/29)

**Comment by connortann** [comment]
@thatlittleboy I think the waterfall plot tests are not fully fixed (from #62), as they still fail on python 3.7.

Related: #69, #73
