### ISSUE TITLE
Bump package version to e.g., 0.41.0.9000

### ISSUE THREAD

**Issue by GegznaV** [dsgibbons/shap#78]
Please, change the version on this package (at least temporarily) so that after installation it was clear that the version from particularly this repo.

**Comment by rfali** [comment]
@dsgibbons As a new SHAP user, I am also confused whether this fork has a corresponding package or not. On PyPI, there exists a shap2 wiuth version 0.42.0, but I am not sure if that is this repo or something else (the homepage points to original shap but that is still at 0.41.0).

Also, the README keeps the original pypi installation
`pip install shap` 
which would install the original SHAP and not this fork?

Confused.

**Comment by dsgibbons** [comment]
@rfali This fork has not been released yet. We are currently trying to merge our changes with [slundberg/shap](https://github.com/slundberg/shap) so as to not fracture the SHAP userbase. For now, please install this fork via:

```pip install git+https://github.com/dsgibbons/shap.git```

I have raised a PR #95 to make this more obvious in the README.

**Comment by dsgibbons** [comment]
Thank you for your interest in this fork @GegznaV. We now have write access at [slundberg/shap](https://github.com/slundberg/shap) and will package our changes into a release over there.

**Comment by rfali** [comment]
@dsgibbons would the fork still exist, or will everything be merged into the original repo?

**Comment by dsgibbons** [comment]
@rfali Yes to both. Everything will be merged into the original repo. A SHAP organisation will eventually be created to ensure the project's long-term health. This fork will still exist, but mainly just as a place to write my own contributions before raising PRs with the main project.
