### ISSUE TITLE
Generate and publish documentation

### ISSUE THREAD

**Issue by thatlittleboy** [dsgibbons/shap#83]
Now that tests are passing (🎉), let's also turn on documentation, so that we can verify that the docs are rendered properly in future PRs. (I'm intending to submit some PRs to fix documentation, typos, formatting fixes etc.).

E.g. related PR slundberg#2020 needs to be ported over.

**Comment by dsgibbons** [comment]
how's this? https://shap-community.readthedocs.io/en/latest/

**Comment by thatlittleboy** [comment]
Looks great @dsgibbons , thank you!

Would be nice to have the following as well, I can attempt this over the weekend if no one takes this up.

- [ ] modify GH action workflow to build and publish docs in pull requests
- [ ] add link to README and github repo, as necessary

**Comment by thatlittleboy** [comment]
Closing this issue, resolved by #93.
